root = "."
tmp_dir = "./tmp"
[build]
pre_cmd = ["pwd"]
cmd = "go build -o ./tmp/main ./cmd/runner_web"
full_bin = 'DATABASE_URL="postgresql://localhost/DAG" MONGO_URI="mongodb://127.0.0.1:27017/dags?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.4.2?statusColor=686B6F&env=local&name=Local%20MongoDB&tLSMode=0&usePrivateKey=false&safeModeLevel=0&advancedSafeModeLevel=0&driverVersion=0&lazyload=false" ./tmp/main'
log = "air.log"

[misc]
clean_on_exit = true