root = "."
tmp_dir = "./tmp"
[build]
pre_cmd = ["pwd"]
cmd = "go build -o ./tmp/main ./cmd/runner_web"
full_bin = "DATABASE_URL=postgresql://localhost/DAG ./tmp/main"
log = "air.log"

[misc]
clean_on_exit = true